name: Parent Workflow
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      myapp:
        image: ghcr.io/honeymakhija/cbd3345_ica2-honey/myapp-image1:latest
        ports:
          - 8080:8080
        options: --entrypoint "python -m test_app" 

    
    steps:
      - name: Use custom action to checkout branch
        uses: honeymakhija/cbd3345_ica2-honey@main
        with:
          branch: "main"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest test_app.py

      - name: Archive test file
        uses: actions/upload-artifact@v2
        with:
          name: test-file
          path: test_file.txt
