name: Parent Workflow

on:
  push:
    branches: [main]

jobs:
  trigger_child_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Child Workflow
        uses: actions/github-script@v4
        with:
          script: |
            const childWorkflow = await github.actions.createWorkflowDispatch({
              workflow_id: 'child.yml', // The name of your child workflow file
              ref: 'main', // The branch where the child workflow will run
            });
            console.log(`Child workflow run ID: ${childWorkflow.data.id}`);
